### ISSUE TITLE
missing flag private-key

### ISSUE THREAD

**Issue by islander** [jingweno/upterm#55]
Hello, I'm trying to use self-hosted server, after deployment I can host sessions from same machine that I've run `terraform` deployment. But other machine returns this error:

```
# upterm host --server wss://<deleted>.herokuapp.com -- bash
Error: 1 error occurred:
	* missing flag --private-key
```

Where I can get this private key?

**Comment by islander** [comment]
Ah, I see, `upterm` just using `.ssh/id_rsa`. Nevermind =)

**Comment by jingweno** [comment]
@islander Yeah, by default, `upterm` points to `~/.ssh/id_rsa` to sign ssh requests. You can point to a custom key path.
