### ISSUE TITLE
Cannot build in Windows inside MINGW32 bash session

### ISSUE THREAD

**Issue by Dnm-28** [jingweno/upterm#56]
Hello!

I'm unable to build from sources for Windows running inside a bash session of Mingw32:

````
$ go build ./cmd/upterm/...
# github.com/jingweno/upterm/host/internal
host\internal\command.go:86:21: undefined: syscall.SIGWINCH
host\internal\command.go:87:9: undefined: syscall.SIGWINCH
host\internal\pty.go:13:12: undefined: pty.Start
host\internal\pty.go:33:9: undefined: pty.Getsize
host\internal\pty.go:54:11: undefined: pty.Winsize
host\internal\pty.go:58:9: undefined: pty.Setsize
```

**Comment by jingweno** [comment]
@Dnm-28 `upterm` is never tested on windows. There may be stuff that doesn't work. Would running upterm in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) an option?

**Comment by shackra** [comment]
> @Dnm-28 `upterm` is never tested on windows. There may be stuff that doesn't work. Would running upterm in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) an option?

hi, I'm friend with OP and saw this bug happen. We could try that and see what happens.

**Comment by shackra** [comment]
indeed, WSL is the way to go.

You can close this issue now.

**Comment by jingweno** [comment]
Closing this issue because windows support is planned for the future.

**Comment by rollingmoai** [comment]
The issue still persists. WSL is not an option for me, unfortunately, and everything should run natively on Windows.
